@startuml jissyu6_1
actor ユーザ
boundary ブラウザ
control web.php
control jissyu6_1Controller
entity Person
boundary index.blade.php
boundary show.blade.php

ユーザ -> ブラウザ:該当ページをリクエスト[/jissyu13]
ブラウザ -> web.php:GET[/jissyu13]
web.php -> jissyu6_1Controller:@index
jissyu6_1Controller -> Person:all()
Person --> jissyu6_1Controller
jissyu6_1Controller -> index.blade.php
ユーザ -> ブラウザ:検索ボタンを押下
ブラウザ -> web.php:GET[/jissyu13/find]
web.php -> jissyu6_1Controller:@find
jissyu6_1Controller -> Person:where()->first()
Person --> jissyu6_1Controller
jissyu6_1Controller -> show.blade.php
@enduml